apiVersion: apps/v1
kind: Deployment
metadata:
  name: aplikacja2
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: aplikacja2
  template:
    metadata:
      labels:
        app:
          aplikacja2 
    spec:
      containers:
        - image: jakubstopa/aplikacja2:latest
          name: aplikacja2
          volumeMounts:
            - name: config
              mountPath: "/"
              readOnly: true
          resources:
            requests:
              cpu: 100m
              memory: 64Mi
            limits:
              cpu: 200m
              memory: 128Mi
      volumes:
        - name: config
          configMap:
            name: rest_api_docker-config