rabbitmq:
  login: "guest"
  password: "guest"
  address: "rabbitmq"
  port: "15672"
  queuename: "kolejka"

aplikacja1:
  port: "5000"
  function: "add"

redis:
  address: "redis"
  port: "6379"

aplikacja3:
  port: "5001"
  function: "size"