apiVersion: apps/v1
kind: Deployment
metadata:
  name: rd
spec:
  selector:
    matchLabels:
      app: rd
  template:
    metadata:
      labels:
        app: rd
    spec:
      containers:
      - name: rd
        image: redis:latest
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 6379
